# Generated by Django 5.0.4 on 2024-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_artikel_bestellung_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='bild',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
